version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./src:/var/www
    networks:
      - laravel
  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www
    depends_on:
      - app
      - mysql
    networks:
      - laravel
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Vodanhphai123@
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - laravel
networks:
  laravel:

