version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    # command: ./app.sh
    volumes:
      - ./src:/var/www
    networks:
      - laravel
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - ${APP_PORT}:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www
    depends_on:
      - app
      - mysql
    networks:
      - laravel
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - laravel
networks:
  laravel:

